# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='Anonymous', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 12, 25, 0, 766000), verbose_name='date created'),
        ),
    ]
