# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160609_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 12, 42, 27, 498000), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=140),
        ),
    ]
