# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160609_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 12, 44, 4, 306000), verbose_name='date created'),
        ),
    ]
